[
  import_deps: [:typedstruct],
  plugins: [Recode.FormatterPlugin],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 98,
  locals_without_parens: [
    agent: 1,
    stage: 1,
    using: 1,
    with_params: 1,
    inputs: 1,
    with_input: 1,
    message: 2,
    text_part: 1,
    data_part: 1,
    file_part: 1,
    expect_output: 1,
    temperature: 1,
    top_p: 1,
    frequency_penalty: 1,
    presence_penalty: 1,
    structured_response: 1,
    thinking_budget: 1,
    depends_on: 1,
    tool: 1,
    module: 1,
    name: 1,
    description: 1,
    parameters: 1,
    api_key: 1,
    tools: 1,
    memory_source: 3
  ],
  export: [
    locals_without_parens: [
      agent: 1,
      stage: 1,
      using: 1,
      with_params: 1,
      inputs: 1,
      with_input: 1,
      message: 2,
      text_part: 1,
      data_part: 1,
      file_part: 1,
      expect_output: 1,
      temperature: 1,
      top_p: 1,
      frequency_penalty: 1,
      presence_penalty: 1,
      structured_response: 1,
      thinking_budget: 1,
      tool: 1,
      module: 1,
      name: 1,
      description: 1,
      parameters: 1,
      api_key: 1,
      tools: 1,
      memory_source: 3
    ]
  ]
]
